### ISSUE TITLE
Podux Theme wrong technology

### ISSUE THREAD

**Issue by DannieBGoode** [statichunt/statichunt#29]
https://github.com/statichunt/statichunt/blob/d6a2444f797eb62bea74d349310099684d18b4dc/content/themes/astro-podux.md?plain=1#L10C9-L10C9

It doesn't seem like that theme is made in Astro, if you go the[ linked repository](https://github.com/Johnkat-Mj/podcas-landing-page) you'll find:

- TailwindCSS 3
- NUXT 3

**Comment by tflijon** [comment]
DannieBGoode, Thanks For your suggestion. I solved it.
