### ISSUE TITLE
Is there a way to change the thumbnail image?

### ISSUE THREAD

**Issue by poeck** [statichunt/statichunt#48]
I am the creator of PortfolioOS (https://statichunt.com/themes/nextjs-portfolio-os). It shows this thumbnail at the moment: ![Screenshot_20240525-154314.png](https://github.com/statichunt/statichunt/assets/69417027/9001e5c6-ed14-447f-bd41-49dda15c5159)

Is there already a way to use a custom thumbnail image? If not, can I implement a new 'thumbnail' option in the themes configs where you can provide a custom url to the thumbnail?

**Comment by tfsomrat** [comment]
Hey @poeck, you can create a PR here https://github.com/statichunt/statichunt-images/tree/main/themes
